language: node_js
node_js:
    - 12
    - 10
    - 8

cache: false

script:
  - npm run bootstrap
  - npm run lint
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false

